version: '2'

services:
    # react:
    #     build: ./client
    #     ports:
    #         - 5173:5173
    #     volumes:
    #         - ./client:/app/frontend
    #     command: npm run dev
    flask:
        restart: unless-stopped
        container_name: datalink_flask
        build:
            context: .
            dockerfile: ./Dockerfile.flask
        environment:
            - OPENAI_API_KEY=OPENAI_API_KEY
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            - ./backend:/app/backend
        command: python main.py

    nginx: 
        restart: unless-stopped
        container_name: datalink_nginx
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        ports:
            - 80:80
        volumes:
            # - ./backend/django_static:/app/backend/server/django_static
            # - ./backend/media:/app/backend/server/media
            - ./nginx/development:/etc/nginx/conf.d
        depends_on:
            # - react
            - flask

    # rmq:
    #     image: rabbitmq:3.10-management
    #     restart: always
    #     container_name: datalink_rmq
    #     environment:
    #       - RABBITMQ_DEFAULT_USER=${RMQ_USER}
    #       - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
    #     volumes:
    #       - rabbitmq_data_volume:/var/lib/rabbitmq/
    #     ports:
    #       - 1234:15672
    #       - 5671-5672:5671-5672
    #     env_file:
    #         - ./.env

# volumes:
#     static_volume: {}
#     rabbitmq_data_volume: {}